platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/ssoca
    tag: ci-build
inputs:
- name: repo
- name: golang
outputs:
- name: repo
  path: repo-output
run:
  path: repo/ci/tasks/upgrade-go-in-build-image/execute.sh
