// Code generated by counterfeiter. DO NOT EDIT.
package dynamicvaluefakes

import (
	"net/http"
	"sync"

	"github.com/dpb587/ssoca/auth"
	"github.com/dpb587/ssoca/server/service/dynamicvalue"
)

type FakeMultiValue struct {
	EvaluateStub        func(*http.Request, *auth.Token) ([]string, error)
	evaluateMutex       sync.RWMutex
	evaluateArgsForCall []struct {
		arg1 *http.Request
		arg2 *auth.Token
	}
	evaluateReturns struct {
		result1 []string
		result2 error
	}
	evaluateReturnsOnCall map[int]struct {
		result1 []string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMultiValue) Evaluate(arg1 *http.Request, arg2 *auth.Token) ([]string, error) {
	fake.evaluateMutex.Lock()
	ret, specificReturn := fake.evaluateReturnsOnCall[len(fake.evaluateArgsForCall)]
	fake.evaluateArgsForCall = append(fake.evaluateArgsForCall, struct {
		arg1 *http.Request
		arg2 *auth.Token
	}{arg1, arg2})
	fake.recordInvocation("Evaluate", []interface{}{arg1, arg2})
	fake.evaluateMutex.Unlock()
	if fake.EvaluateStub != nil {
		return fake.EvaluateStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.evaluateReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMultiValue) EvaluateCallCount() int {
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	return len(fake.evaluateArgsForCall)
}

func (fake *FakeMultiValue) EvaluateCalls(stub func(*http.Request, *auth.Token) ([]string, error)) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = stub
}

func (fake *FakeMultiValue) EvaluateArgsForCall(i int) (*http.Request, *auth.Token) {
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	argsForCall := fake.evaluateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMultiValue) EvaluateReturns(result1 []string, result2 error) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = nil
	fake.evaluateReturns = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeMultiValue) EvaluateReturnsOnCall(i int, result1 []string, result2 error) {
	fake.evaluateMutex.Lock()
	defer fake.evaluateMutex.Unlock()
	fake.EvaluateStub = nil
	if fake.evaluateReturnsOnCall == nil {
		fake.evaluateReturnsOnCall = make(map[int]struct {
			result1 []string
			result2 error
		})
	}
	fake.evaluateReturnsOnCall[i] = struct {
		result1 []string
		result2 error
	}{result1, result2}
}

func (fake *FakeMultiValue) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.evaluateMutex.RLock()
	defer fake.evaluateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMultiValue) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ dynamicvalue.MultiValue = new(FakeMultiValue)
