platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/ssoca
    tag: ci-docs
inputs:
- name: repo
- name: artifacts
- name: hugo-site
outputs:
- name: public
run:
  path: repo/ci/tasks/build-docs/execute.sh
