// This file was generated by counterfeiter
package httpclientfakes

import (
	"io"
	"sync"

	"github.com/cheggaaa/pb"
	"github.com/dpb587/ssoca/service/download/api"
	"github.com/dpb587/ssoca/service/download/httpclient"
)

type FakeClient struct {
	GetListStub        func() (api.ListResponse, error)
	getListMutex       sync.RWMutex
	getListArgsForCall []struct{}
	getListReturns     struct {
		result1 api.ListResponse
		result2 error
	}
	DownloadStub        func(string, io.ReadWriteSeeker, *pb.ProgressBar) error
	downloadMutex       sync.RWMutex
	downloadArgsForCall []struct {
		arg1 string
		arg2 io.ReadWriteSeeker
		arg3 *pb.ProgressBar
	}
	downloadReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) GetList() (api.ListResponse, error) {
	fake.getListMutex.Lock()
	fake.getListArgsForCall = append(fake.getListArgsForCall, struct{}{})
	fake.recordInvocation("GetList", []interface{}{})
	fake.getListMutex.Unlock()
	if fake.GetListStub != nil {
		return fake.GetListStub()
	}
	return fake.getListReturns.result1, fake.getListReturns.result2
}

func (fake *FakeClient) GetListCallCount() int {
	fake.getListMutex.RLock()
	defer fake.getListMutex.RUnlock()
	return len(fake.getListArgsForCall)
}

func (fake *FakeClient) GetListReturns(result1 api.ListResponse, result2 error) {
	fake.GetListStub = nil
	fake.getListReturns = struct {
		result1 api.ListResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) Download(arg1 string, arg2 io.ReadWriteSeeker, arg3 *pb.ProgressBar) error {
	fake.downloadMutex.Lock()
	fake.downloadArgsForCall = append(fake.downloadArgsForCall, struct {
		arg1 string
		arg2 io.ReadWriteSeeker
		arg3 *pb.ProgressBar
	}{arg1, arg2, arg3})
	fake.recordInvocation("Download", []interface{}{arg1, arg2, arg3})
	fake.downloadMutex.Unlock()
	if fake.DownloadStub != nil {
		return fake.DownloadStub(arg1, arg2, arg3)
	}
	return fake.downloadReturns.result1
}

func (fake *FakeClient) DownloadCallCount() int {
	fake.downloadMutex.RLock()
	defer fake.downloadMutex.RUnlock()
	return len(fake.downloadArgsForCall)
}

func (fake *FakeClient) DownloadArgsForCall(i int) (string, io.ReadWriteSeeker, *pb.ProgressBar) {
	fake.downloadMutex.RLock()
	defer fake.downloadMutex.RUnlock()
	return fake.downloadArgsForCall[i].arg1, fake.downloadArgsForCall[i].arg2, fake.downloadArgsForCall[i].arg3
}

func (fake *FakeClient) DownloadReturns(result1 error) {
	fake.DownloadStub = nil
	fake.downloadReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getListMutex.RLock()
	defer fake.getListMutex.RUnlock()
	fake.downloadMutex.RLock()
	defer fake.downloadMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ httpclient.Client = new(FakeClient)
