// Code generated by counterfeiter. DO NOT EDIT.
package servicefakes

import (
	"sync"

	"github.com/dpb587/ssoca/server/service"
	servicessoca "github.com/dpb587/ssoca/service"
)

type FakeFactory struct {
	CreateStub        func(servicessoca.Type, string, map[string]interface{}) (service.Service, error)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 servicessoca.Type
		arg2 string
		arg3 map[string]interface{}
	}
	createReturns struct {
		result1 service.Service
		result2 error
	}
	createReturnsOnCall map[int]struct {
		result1 service.Service
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeFactory) Create(arg1 servicessoca.Type, arg2 string, arg3 map[string]interface{}) (service.Service, error) {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 servicessoca.Type
		arg2 string
		arg3 map[string]interface{}
	}{arg1, arg2, arg3})
	fake.recordInvocation("Create", []interface{}{arg1, arg2, arg3})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		return fake.CreateStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.createReturns.result1, fake.createReturns.result2
}

func (fake *FakeFactory) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeFactory) CreateArgsForCall(i int) (servicessoca.Type, string, map[string]interface{}) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].arg1, fake.createArgsForCall[i].arg2, fake.createArgsForCall[i].arg3
}

func (fake *FakeFactory) CreateReturns(result1 service.Service, result2 error) {
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 service.Service
		result2 error
	}{result1, result2}
}

func (fake *FakeFactory) CreateReturnsOnCall(i int, result1 service.Service, result2 error) {
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 service.Service
			result2 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 service.Service
		result2 error
	}{result1, result2}
}

func (fake *FakeFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ service.Factory = new(FakeFactory)
