// This file was generated by counterfeiter
package clientfakes

import (
	"sync"

	"github.com/dpb587/ssoca/client"
)

type FakeExecutableFinder struct {
	FindStub        func() (string, error)
	findMutex       sync.RWMutex
	findArgsForCall []struct{}
	findReturns     struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeExecutableFinder) Find() (string, error) {
	fake.findMutex.Lock()
	fake.findArgsForCall = append(fake.findArgsForCall, struct{}{})
	fake.recordInvocation("Find", []interface{}{})
	fake.findMutex.Unlock()
	if fake.FindStub != nil {
		return fake.FindStub()
	}
	return fake.findReturns.result1, fake.findReturns.result2
}

func (fake *FakeExecutableFinder) FindCallCount() int {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return len(fake.findArgsForCall)
}

func (fake *FakeExecutableFinder) FindReturns(result1 string, result2 error) {
	fake.FindStub = nil
	fake.findReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeExecutableFinder) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeExecutableFinder) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ client.ExecutableFinder = new(FakeExecutableFinder)
