// Code generated by counterfeiter. DO NOT EDIT.
package certauthfakes

import (
	"crypto/x509"
	"sync"

	"github.com/dpb587/ssoca/certauth"
	"github.com/sirupsen/logrus"
	"golang.org/x/crypto/ssh"
)

type FakeProvider struct {
	GetCertificateStub        func() (*x509.Certificate, error)
	getCertificateMutex       sync.RWMutex
	getCertificateArgsForCall []struct {
	}
	getCertificateReturns struct {
		result1 *x509.Certificate
		result2 error
	}
	getCertificateReturnsOnCall map[int]struct {
		result1 *x509.Certificate
		result2 error
	}
	GetCertificatePEMStub        func() (string, error)
	getCertificatePEMMutex       sync.RWMutex
	getCertificatePEMArgsForCall []struct {
	}
	getCertificatePEMReturns struct {
		result1 string
		result2 error
	}
	getCertificatePEMReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	NameStub        func() string
	nameMutex       sync.RWMutex
	nameArgsForCall []struct {
	}
	nameReturns struct {
		result1 string
	}
	nameReturnsOnCall map[int]struct {
		result1 string
	}
	SignCertificateStub        func(*x509.Certificate, interface{}, logrus.Fields) ([]byte, error)
	signCertificateMutex       sync.RWMutex
	signCertificateArgsForCall []struct {
		arg1 *x509.Certificate
		arg2 interface{}
		arg3 logrus.Fields
	}
	signCertificateReturns struct {
		result1 []byte
		result2 error
	}
	signCertificateReturnsOnCall map[int]struct {
		result1 []byte
		result2 error
	}
	SignSSHCertificateStub        func(*ssh.Certificate, logrus.Fields) error
	signSSHCertificateMutex       sync.RWMutex
	signSSHCertificateArgsForCall []struct {
		arg1 *ssh.Certificate
		arg2 logrus.Fields
	}
	signSSHCertificateReturns struct {
		result1 error
	}
	signSSHCertificateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProvider) GetCertificate() (*x509.Certificate, error) {
	fake.getCertificateMutex.Lock()
	ret, specificReturn := fake.getCertificateReturnsOnCall[len(fake.getCertificateArgsForCall)]
	fake.getCertificateArgsForCall = append(fake.getCertificateArgsForCall, struct {
	}{})
	fake.recordInvocation("GetCertificate", []interface{}{})
	fake.getCertificateMutex.Unlock()
	if fake.GetCertificateStub != nil {
		return fake.GetCertificateStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getCertificateReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProvider) GetCertificateCallCount() int {
	fake.getCertificateMutex.RLock()
	defer fake.getCertificateMutex.RUnlock()
	return len(fake.getCertificateArgsForCall)
}

func (fake *FakeProvider) GetCertificateCalls(stub func() (*x509.Certificate, error)) {
	fake.getCertificateMutex.Lock()
	defer fake.getCertificateMutex.Unlock()
	fake.GetCertificateStub = stub
}

func (fake *FakeProvider) GetCertificateReturns(result1 *x509.Certificate, result2 error) {
	fake.getCertificateMutex.Lock()
	defer fake.getCertificateMutex.Unlock()
	fake.GetCertificateStub = nil
	fake.getCertificateReturns = struct {
		result1 *x509.Certificate
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) GetCertificateReturnsOnCall(i int, result1 *x509.Certificate, result2 error) {
	fake.getCertificateMutex.Lock()
	defer fake.getCertificateMutex.Unlock()
	fake.GetCertificateStub = nil
	if fake.getCertificateReturnsOnCall == nil {
		fake.getCertificateReturnsOnCall = make(map[int]struct {
			result1 *x509.Certificate
			result2 error
		})
	}
	fake.getCertificateReturnsOnCall[i] = struct {
		result1 *x509.Certificate
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) GetCertificatePEM() (string, error) {
	fake.getCertificatePEMMutex.Lock()
	ret, specificReturn := fake.getCertificatePEMReturnsOnCall[len(fake.getCertificatePEMArgsForCall)]
	fake.getCertificatePEMArgsForCall = append(fake.getCertificatePEMArgsForCall, struct {
	}{})
	fake.recordInvocation("GetCertificatePEM", []interface{}{})
	fake.getCertificatePEMMutex.Unlock()
	if fake.GetCertificatePEMStub != nil {
		return fake.GetCertificatePEMStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getCertificatePEMReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProvider) GetCertificatePEMCallCount() int {
	fake.getCertificatePEMMutex.RLock()
	defer fake.getCertificatePEMMutex.RUnlock()
	return len(fake.getCertificatePEMArgsForCall)
}

func (fake *FakeProvider) GetCertificatePEMCalls(stub func() (string, error)) {
	fake.getCertificatePEMMutex.Lock()
	defer fake.getCertificatePEMMutex.Unlock()
	fake.GetCertificatePEMStub = stub
}

func (fake *FakeProvider) GetCertificatePEMReturns(result1 string, result2 error) {
	fake.getCertificatePEMMutex.Lock()
	defer fake.getCertificatePEMMutex.Unlock()
	fake.GetCertificatePEMStub = nil
	fake.getCertificatePEMReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) GetCertificatePEMReturnsOnCall(i int, result1 string, result2 error) {
	fake.getCertificatePEMMutex.Lock()
	defer fake.getCertificatePEMMutex.Unlock()
	fake.GetCertificatePEMStub = nil
	if fake.getCertificatePEMReturnsOnCall == nil {
		fake.getCertificatePEMReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getCertificatePEMReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) Name() string {
	fake.nameMutex.Lock()
	ret, specificReturn := fake.nameReturnsOnCall[len(fake.nameArgsForCall)]
	fake.nameArgsForCall = append(fake.nameArgsForCall, struct {
	}{})
	fake.recordInvocation("Name", []interface{}{})
	fake.nameMutex.Unlock()
	if fake.NameStub != nil {
		return fake.NameStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.nameReturns
	return fakeReturns.result1
}

func (fake *FakeProvider) NameCallCount() int {
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	return len(fake.nameArgsForCall)
}

func (fake *FakeProvider) NameCalls(stub func() string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = stub
}

func (fake *FakeProvider) NameReturns(result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	fake.nameReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeProvider) NameReturnsOnCall(i int, result1 string) {
	fake.nameMutex.Lock()
	defer fake.nameMutex.Unlock()
	fake.NameStub = nil
	if fake.nameReturnsOnCall == nil {
		fake.nameReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.nameReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeProvider) SignCertificate(arg1 *x509.Certificate, arg2 interface{}, arg3 logrus.Fields) ([]byte, error) {
	fake.signCertificateMutex.Lock()
	ret, specificReturn := fake.signCertificateReturnsOnCall[len(fake.signCertificateArgsForCall)]
	fake.signCertificateArgsForCall = append(fake.signCertificateArgsForCall, struct {
		arg1 *x509.Certificate
		arg2 interface{}
		arg3 logrus.Fields
	}{arg1, arg2, arg3})
	fake.recordInvocation("SignCertificate", []interface{}{arg1, arg2, arg3})
	fake.signCertificateMutex.Unlock()
	if fake.SignCertificateStub != nil {
		return fake.SignCertificateStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.signCertificateReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeProvider) SignCertificateCallCount() int {
	fake.signCertificateMutex.RLock()
	defer fake.signCertificateMutex.RUnlock()
	return len(fake.signCertificateArgsForCall)
}

func (fake *FakeProvider) SignCertificateCalls(stub func(*x509.Certificate, interface{}, logrus.Fields) ([]byte, error)) {
	fake.signCertificateMutex.Lock()
	defer fake.signCertificateMutex.Unlock()
	fake.SignCertificateStub = stub
}

func (fake *FakeProvider) SignCertificateArgsForCall(i int) (*x509.Certificate, interface{}, logrus.Fields) {
	fake.signCertificateMutex.RLock()
	defer fake.signCertificateMutex.RUnlock()
	argsForCall := fake.signCertificateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeProvider) SignCertificateReturns(result1 []byte, result2 error) {
	fake.signCertificateMutex.Lock()
	defer fake.signCertificateMutex.Unlock()
	fake.SignCertificateStub = nil
	fake.signCertificateReturns = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) SignCertificateReturnsOnCall(i int, result1 []byte, result2 error) {
	fake.signCertificateMutex.Lock()
	defer fake.signCertificateMutex.Unlock()
	fake.SignCertificateStub = nil
	if fake.signCertificateReturnsOnCall == nil {
		fake.signCertificateReturnsOnCall = make(map[int]struct {
			result1 []byte
			result2 error
		})
	}
	fake.signCertificateReturnsOnCall[i] = struct {
		result1 []byte
		result2 error
	}{result1, result2}
}

func (fake *FakeProvider) SignSSHCertificate(arg1 *ssh.Certificate, arg2 logrus.Fields) error {
	fake.signSSHCertificateMutex.Lock()
	ret, specificReturn := fake.signSSHCertificateReturnsOnCall[len(fake.signSSHCertificateArgsForCall)]
	fake.signSSHCertificateArgsForCall = append(fake.signSSHCertificateArgsForCall, struct {
		arg1 *ssh.Certificate
		arg2 logrus.Fields
	}{arg1, arg2})
	fake.recordInvocation("SignSSHCertificate", []interface{}{arg1, arg2})
	fake.signSSHCertificateMutex.Unlock()
	if fake.SignSSHCertificateStub != nil {
		return fake.SignSSHCertificateStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.signSSHCertificateReturns
	return fakeReturns.result1
}

func (fake *FakeProvider) SignSSHCertificateCallCount() int {
	fake.signSSHCertificateMutex.RLock()
	defer fake.signSSHCertificateMutex.RUnlock()
	return len(fake.signSSHCertificateArgsForCall)
}

func (fake *FakeProvider) SignSSHCertificateCalls(stub func(*ssh.Certificate, logrus.Fields) error) {
	fake.signSSHCertificateMutex.Lock()
	defer fake.signSSHCertificateMutex.Unlock()
	fake.SignSSHCertificateStub = stub
}

func (fake *FakeProvider) SignSSHCertificateArgsForCall(i int) (*ssh.Certificate, logrus.Fields) {
	fake.signSSHCertificateMutex.RLock()
	defer fake.signSSHCertificateMutex.RUnlock()
	argsForCall := fake.signSSHCertificateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeProvider) SignSSHCertificateReturns(result1 error) {
	fake.signSSHCertificateMutex.Lock()
	defer fake.signSSHCertificateMutex.Unlock()
	fake.SignSSHCertificateStub = nil
	fake.signSSHCertificateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeProvider) SignSSHCertificateReturnsOnCall(i int, result1 error) {
	fake.signSSHCertificateMutex.Lock()
	defer fake.signSSHCertificateMutex.Unlock()
	fake.SignSSHCertificateStub = nil
	if fake.signSSHCertificateReturnsOnCall == nil {
		fake.signSSHCertificateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.signSSHCertificateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getCertificateMutex.RLock()
	defer fake.getCertificateMutex.RUnlock()
	fake.getCertificatePEMMutex.RLock()
	defer fake.getCertificatePEMMutex.RUnlock()
	fake.nameMutex.RLock()
	defer fake.nameMutex.RUnlock()
	fake.signCertificateMutex.RLock()
	defer fake.signCertificateMutex.RUnlock()
	fake.signSSHCertificateMutex.RLock()
	defer fake.signSSHCertificateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ certauth.Provider = new(FakeProvider)
