platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/ssoca
    tag: ci-build
inputs:
- name: repo
- name: version
- name: artifacts
outputs:
- name: release
run:
  path: repo/ci/tasks/build-release/execute.sh
